### ISSUE TITLE
Watermark extraction rate does not decrease

### ISSUE THREAD

**Issue by zrsandwj1314** [GuanlinLee/warfare#1]
![image](https://github.com/GuanlinLee/warfare/assets/56124892/e23bee7e-b593-4085-bcdc-b34f00d57748) 
![image](https://github.com/GuanlinLee/warfare/assets/56124892/1280bae9-4971-4b7f-99dd-e6cad2173630)
Hello, according to the experimental setup in your paper on the Celeba dataset, the StegaStamp training effect, diffusion model output under large noise, and watermark extraction effect are basically the same. However, the watermark extraction rate has not decreased during the training of the generative adversarial network. I see that your paper showed a decrease at 400 epochs.

**Comment by GuanlinLee** [comment]
It seems the Dloss is too low. You can try to increase the weights of the discriminator. We notice the training process of the GAN is not stable. So, try more weight combinations, which are related to your devices and datasets. The hyperparameters in our paper are used in our experiments, but could not be suitable for all users.

**Comment by zrsandwj1314** [comment]
Thank you very much for your answer. I will try more weight combinations. Thank you again for your research. I have learned a lot!

**Comment by GuanlinLee** [comment]
Thanks for your interest.
