### ISSUE TITLE
pretrained model checkpoint of ema_lsun.ckpt

### ISSUE THREAD

**Issue by yfjn** [GuanlinLee/warfare#2]
Hello, I appreciate your work. Could you please provide `ema_lsun.ckpt`? I don't know where I can download it. Thanks!

**Comment by GuanlinLee** [comment]
Please try to use the model from https://huggingface.co/fusing/ddpm-lsun-bedroom-ema. I think the original Google Drive link is missing now.

**Comment by yfjn** [comment]
Thank you very much!

**Comment by yfjn** [comment]
I'm sorry, there is another mistake. `self.env = lmdb.open(root, max_readers=1, readonly=True, lock=False, readahead=False, meminit=False)
lmdb.Error: ./data/bedroom_train_lmdb: No such file or directory`. When I try to download the dataset myself. I visit `http://www.yf.io/p/lsun` and got HTTP Error 404: Not Found. Where can I download it? Thanks again!
I successfully ran warfare on 64×64 celeba dataset, and now I want to try it on 256×256 dataset.

**Comment by GuanlinLee** [comment]
Could you try to use HuggingFace for dataset downloading? The dataset can be found in https://huggingface.co/datasets/pcuenq/lsun-bedrooms.

**Comment by yfjn** [comment]
I downloaded the dataset and renamed it `bedroom_train_lmdb` in the project's `data` folder, but still reported the error `lmdb.Error: ./data/bedroom_train_lmdb: No such file or directory`.
I found lmdb is a kind of database, now I found a link to download the lmdb, I will try it again.

**Comment by yfjn** [comment]
I can run successfully. I found that it needs 22 days to diffusion purify 10,000 images, so I intend to use the fewshot setting of 500 images. I have read the paper that warfare has strong generalization ability of small samples, which can meet the practical application.

**Comment by GuanlinLee** [comment]
Yes, you could try to use the few-shot setting. But I am not very sure how it works on different image domains. We only test it on the same image domain but with different watermarks.

BTW, the speed of the diffusion model depends on your GPUs. We adopt A100 in our experiments.

**Comment by yfjn** [comment]
I use 3090 to run on 256×256 LSUN dataset. Last time it ran much faster on 64×64 CelebA dataset because of image size.
By the way, I wonder if the result in Table 5 is trained on StegaStamp, and then few shot on WGAN-div and EDM watermark schemes, or few shot on different watermark binary information of StegaStamp?

**Comment by GuanlinLee** [comment]
They are few-shot results on different watermark binary information of StegaStamp. The results of WGAN-div and EDM are in Table 6.

**Comment by yfjn** [comment]
OK, thanks for your early reply!
